import { PageProps } from "app/interfaces";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: 'Your goals',
};

export default function Goals(props: PageProps) {
  return (
    <>
      <h2>Your goals page</h2>

      <p style={{ marginBottom: 30 }}>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis tenetur ut voluptatem omnis quibusdam praesentium? Error inventore adipisci consectetur temporibus at aperiam? Animi alias ipsam quibusdam accusantium magnam? Aperiam quam praesentium rem. Voluptatum autem repudiandae repellat asperiores possimus, magni quae iste. Sit nisi placeat similique. Iusto facilis corrupti obcaecati eum?</p>
      <p style={{ marginBottom: 30 }}>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis tenetur ut voluptatem omnis quibusdam praesentium? Error inventore adipisci consectetur temporibus at aperiam? Animi alias ipsam quibusdam accusantium magnam? Aperiam quam praesentium rem. Voluptatum autem repudiandae repellat asperiores possimus, magni quae iste. Sit nisi placeat similique. Iusto facilis corrupti obcaecati eum?</p>
      <p style={{ marginBottom: 30 }}>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis tenetur ut voluptatem omnis quibusdam praesentium? Error inventore adipisci consectetur temporibus at aperiam? Animi alias ipsam quibusdam accusantium magnam? Aperiam quam praesentium rem. Voluptatum autem repudiandae repellat asperiores possimus, magni quae iste. Sit nisi placeat similique. Iusto facilis corrupti obcaecati eum?</p>

      <p style={{ marginBottom: 30 }}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga ducimus tenetur quae, soluta quaerat dolorum omnis architecto est obcaecati eum molestias quisquam a ea officiis. Doloribus error quis assumenda reiciendis esse nesciunt officiis sed ad placeat laudantium. Ducimus atque fugit ut, iure possimus consectetur illo minima molestiae esse nam inventore maxime alias aliquam? Officiis dolorem placeat reprehenderit quos tempora non reiciendis beatae doloribus totam nesciunt soluta facere odio adipisci cumque obcaecati, corporis iusto. Sequi omnis atque ea alias odit inventore placeat! Ut odio ducimus suscipit quam a blanditiis ipsum recusandae saepe dolorem quasi, doloremque aperiam, ullam eius velit alias totam cupiditate esse laudantium dicta nobis vitae, minus facere voluptatem? Omnis, blanditiis corrupti iusto consectetur quas excepturi porro consequuntur illum sapiente non recusandae provident repellat. Dolorem eaque totam accusantium quia dolor esse rerum iusto, laudantium facilis ipsa. Quod atque dolorum tenetur adipisci quibusdam amet, fugiat, magnam fuga minima repellendus sit praesentium? Eos deserunt sequi tempora. Eum et pariatur, eos ad cupiditate tenetur unde voluptatibus accusamus, temporibus doloremque esse id sunt ipsa nemo, corporis exercitationem necessitatibus saepe! Odit vitae beatae aut eum, necessitatibus fuga recusandae amet voluptate. Nostrum id quaerat et eos. Sunt qui dolorum nemo provident impedit. Est blanditiis totam sit.</p>
      <p style={{ marginBottom: 30 }}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga ducimus tenetur quae, soluta quaerat dolorum omnis architecto est obcaecati eum molestias quisquam a ea officiis. Doloribus error quis assumenda reiciendis esse nesciunt officiis sed ad placeat laudantium. Ducimus atque fugit ut, iure possimus consectetur illo minima molestiae esse nam inventore maxime alias aliquam? Officiis dolorem placeat reprehenderit quos tempora non reiciendis beatae doloribus totam nesciunt soluta facere odio adipisci cumque obcaecati, corporis iusto. Sequi omnis atque ea alias odit inventore placeat! Ut odio ducimus suscipit quam a blanditiis ipsum recusandae saepe dolorem quasi, doloremque aperiam, ullam eius velit alias totam cupiditate esse laudantium dicta nobis vitae, minus facere voluptatem? Omnis, blanditiis corrupti iusto consectetur quas excepturi porro consequuntur illum sapiente non recusandae provident repellat. Dolorem eaque totam accusantium quia dolor esse rerum iusto, laudantium facilis ipsa. Quod atque dolorum tenetur adipisci quibusdam amet, fugiat, magnam fuga minima repellendus sit praesentium? Eos deserunt sequi tempora. Eum et pariatur, eos ad cupiditate tenetur unde voluptatibus accusamus, temporibus doloremque esse id sunt ipsa nemo, corporis exercitationem necessitatibus saepe! Odit vitae beatae aut eum, necessitatibus fuga recusandae amet voluptate. Nostrum id quaerat et eos. Sunt qui dolorum nemo provident impedit. Est blanditiis totam sit.</p>
      <p style={{ marginBottom: 30 }}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga ducimus tenetur quae, soluta quaerat dolorum omnis architecto est obcaecati eum molestias quisquam a ea officiis. Doloribus error quis assumenda reiciendis esse nesciunt officiis sed ad placeat laudantium. Ducimus atque fugit ut, iure possimus consectetur illo minima molestiae esse nam inventore maxime alias aliquam? Officiis dolorem placeat reprehenderit quos tempora non reiciendis beatae doloribus totam nesciunt soluta facere odio adipisci cumque obcaecati, corporis iusto. Sequi omnis atque ea alias odit inventore placeat! Ut odio ducimus suscipit quam a blanditiis ipsum recusandae saepe dolorem quasi, doloremque aperiam, ullam eius velit alias totam cupiditate esse laudantium dicta nobis vitae, minus facere voluptatem? Omnis, blanditiis corrupti iusto consectetur quas excepturi porro consequuntur illum sapiente non recusandae provident repellat. Dolorem eaque totam accusantium quia dolor esse rerum iusto, laudantium facilis ipsa. Quod atque dolorum tenetur adipisci quibusdam amet, fugiat, magnam fuga minima repellendus sit praesentium? Eos deserunt sequi tempora. Eum et pariatur, eos ad cupiditate tenetur unde voluptatibus accusamus, temporibus doloremque esse id sunt ipsa nemo, corporis exercitationem necessitatibus saepe! Odit vitae beatae aut eum, necessitatibus fuga recusandae amet voluptate. Nostrum id quaerat et eos. Sunt qui dolorum nemo provident impedit. Est blanditiis totam sit.</p>
      <p style={{ marginBottom: 30 }}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga ducimus tenetur quae, soluta quaerat dolorum omnis architecto est obcaecati eum molestias quisquam a ea officiis. Doloribus error quis assumenda reiciendis esse nesciunt officiis sed ad placeat laudantium. Ducimus atque fugit ut, iure possimus consectetur illo minima molestiae esse nam inventore maxime alias aliquam? Officiis dolorem placeat reprehenderit quos tempora non reiciendis beatae doloribus totam nesciunt soluta facere odio adipisci cumque obcaecati, corporis iusto. Sequi omnis atque ea alias odit inventore placeat! Ut odio ducimus suscipit quam a blanditiis ipsum recusandae saepe dolorem quasi, doloremque aperiam, ullam eius velit alias totam cupiditate esse laudantium dicta nobis vitae, minus facere voluptatem? Omnis, blanditiis corrupti iusto consectetur quas excepturi porro consequuntur illum sapiente non recusandae provident repellat. Dolorem eaque totam accusantium quia dolor esse rerum iusto, laudantium facilis ipsa. Quod atque dolorum tenetur adipisci quibusdam amet, fugiat, magnam fuga minima repellendus sit praesentium? Eos deserunt sequi tempora. Eum et pariatur, eos ad cupiditate tenetur unde voluptatibus accusamus, temporibus doloremque esse id sunt ipsa nemo, corporis exercitationem necessitatibus saepe! Odit vitae beatae aut eum, necessitatibus fuga recusandae amet voluptate. Nostrum id quaerat et eos. Sunt qui dolorum nemo provident impedit. Est blanditiis totam sit.</p>
      <p style={{ marginBottom: 30 }}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga ducimus tenetur quae, soluta quaerat dolorum omnis architecto est obcaecati eum molestias quisquam a ea officiis. Doloribus error quis assumenda reiciendis esse nesciunt officiis sed ad placeat laudantium. Ducimus atque fugit ut, iure possimus consectetur illo minima molestiae esse nam inventore maxime alias aliquam? Officiis dolorem placeat reprehenderit quos tempora non reiciendis beatae doloribus totam nesciunt soluta facere odio adipisci cumque obcaecati, corporis iusto. Sequi omnis atque ea alias odit inventore placeat! Ut odio ducimus suscipit quam a blanditiis ipsum recusandae saepe dolorem quasi, doloremque aperiam, ullam eius velit alias totam cupiditate esse laudantium dicta nobis vitae, minus facere voluptatem? Omnis, blanditiis corrupti iusto consectetur quas excepturi porro consequuntur illum sapiente non recusandae provident repellat. Dolorem eaque totam accusantium quia dolor esse rerum iusto, laudantium facilis ipsa. Quod atque dolorum tenetur adipisci quibusdam amet, fugiat, magnam fuga minima repellendus sit praesentium? Eos deserunt sequi tempora. Eum et pariatur, eos ad cupiditate tenetur unde voluptatibus accusamus, temporibus doloremque esse id sunt ipsa nemo, corporis exercitationem necessitatibus saepe! Odit vitae beatae aut eum, necessitatibus fuga recusandae amet voluptate. Nostrum id quaerat et eos. Sunt qui dolorum nemo provident impedit. Est blanditiis totam sit.</p>

      <h3 id='example'>Example</h3>

      <p>Starting by thinking what are most important things you want to achieve.</p>
    </>
  );
}